stages:
    - check_style
    - test_code
    # - test_and_create_docs
    # - publish_docs

style:
    before_script:
        - python3 -m pip install -U pip setuptools flake8
    script:
        - make style-check
    allow_failure: false
    stage: check_style


tests:
    stage: test_code
    script:
        - tox


#docs:
#    before_script:
#        - python3 -m pip install -U pip setuptools
#        - python3 -m pip install -e .[docs]
#    script:
#        - cd docs
#        - sphinx-build -b html . _build/html
#    stage: test_and_create_docs
#    artifacts:
#           paths:
#             - docs/_build


#publish_docs:
#    script:
#        - publish_docs docs/_build/html $(python3 -c 'import setuptools; setuptools.setup()' --name)
#        - create_index_html
#    stage: publish_docs
#    dependencies:
#          - docs
#    when: manual
#    only:
#        - master
#        - main
