name: Python CI

on:
  push:  # This will trigger the workflow on every push event
    # No branch filters specified, so it will run on all branches

jobs:
  check_style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x  # Replace '3.x' with the desired Python version

      - name: Install dependencies
        run: python -m pip install -U pip setuptools flake8

      - name: Style check
        run: make style-check
    continue-on-error: false

  test_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x  # Replace '3.x' with the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install tox  # Install tox

      - name: Run tests with tox
        run: tox
